=== pshoultz/school/cop4856/hw1/photo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT photo (type, creator, mimetype, keywords, keyword)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT mimetype (#PCDATA)>
<!ELEMENT keywords (keyword*)>
<!ELEMENT keyword (#PCDATA)>

=== pshoultz/school/cop4856/hw1/validate.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE photo SYSTEM "photo.dtd">

<photo>
   <type>hd</type>
   <creator>shoultz</creator>
   <mimetype>text/html</mimetype>
   <location>https://pixabay.com/photos/keyboard-computer-keys-white-886462/ (Links to an external site.)</location>
   <keywords>
      <keyword>color</keyword>
      <keyword>asdfasdf</keyword>
   </keywords>
</photo>

=== pshoultz/school/cop4856/hw1/photo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE photo SYSTEM "photo.dtd">

<photo>
   <type>stock</type>
   <creator>Simon</creator>
   <mimetype>text/html</mimetype>
   <location>https://pixabay.com/photos/keyboard-computer-keys-white-886462/ (Links to an external site.)</location>
   <keywords>
      <keyword>blackandwhite</keyword>
      <keyword>keyboard</keyword>
   </keywords>
</photo>
