=== pshoultz/school/cop4856/project1/gallery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="gallery">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="photo" maxOccurs="unbounded"/>	
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="photo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string"/>
				<xs:element name="type" type="xs:string"/>
				<xs:element ref="creator"/>
				<xs:element name="mimetype" type="xs:string"/>
				<xs:element name="location" type="xs:string"/>
				<xs:element ref="keywords"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="creator">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="url" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="keywords">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="keyword" type="xs:string" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== pshoultz/school/cop4856/project1/gallery1.xml
<?xml version="1.0" encoding="UTF-8" ?>


<gallery xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gallery.xsd">
	<photo>
		<tile>title 1</tile><!-- tile is not part of this schema -->
		<type>stock</type>
		<creator>
			<name>paul</name>
			<url>www.url1.com</url>
		</creator>
		<mimetype>text/html</mimetype>
		<location>https://pixabay.com/photos/keyboard-computer-keys-white-0000000/
			(Links to an external site.)</location>
		<keywords>
			<keyword>apple</keyword>
			<keyword>banana</keyword>
		</keywords>
	</photo>

	<photo>
		<title>title 2</title>
		<type>stock</type>
		<creator>
			<name>mark</name>
			<url>www.url2.com</url>
		</creator>
		<mimetype>text/html</mimetype>
		<location>https://google.com(Links to an external site.)</location>
		<keywords>
			<keyword>cat</keyword>
			<keyword>dog</keyword>
		</keywords>
	</photo>

	<photo>
		<title>title 3</title>
		<type>stock</type>
		<creator>
			<name>david</name>
			<url>www.url3.com</url>
		</creator>
		<mimetype>text/html</mimetype>
		<location>https://amazon.com (Links to an external site.)</location>
		<keywords>
			<keyword>elephant</keyword>
			<keyword>frog</keyword>
		</keywords>
	</photo>
</gallery>
